In [109]:
import torch
import numpy as np
import pandas as pd

In [11]:
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor



In [ ]:
## download data set

In [13]:
training_data = datasets.MNIST(
    root = "data",
    train= False ,
    download=True,
    transform=ToTensor(),
)




In [ ]:
# Download test data from open datasets.


In [15]:
test_data = datasets.MNIST(
    root ="data",
    train=False,
    download=True,
    transform = ToTensor(),
)

In [8]:
batch_size=64
train_dataloader = DataLoader(training_data, batch_size=batch_size)
test_dataloader = DataLoader(test_data, batch_size=batch_size)
print("training data zize: ", len(train_dataloader) *batch_size)
print("test data zize: ", len(test_dataloader) *batch_size)
                             

training data zize:  10048
test data zize:  10048


In [9]:
for X, y in test_dataloader:
    print(f"Shape of X [N, C, H, W]: {X.shape}")
    print(f"Shape of y: {y.shape} {y.dtype}")
    break

Shape of X [N, C, H, W]: torch.Size([64, 1, 28, 28])
Shape of y: torch.Size([64]) torch.int64


In [53]:
#1D tensor
a= torch.tensor([7,3,4,4,5,7])

In [27]:
a.type()

'torch.LongTensor'

In [35]:
a[0:5:2]

tensor([7, 4, 5])

In [37]:
a[:5:2]

tensor([7, 4, 5])

In [39]:
torch.int64

torch.int64

In [49]:
a.dtype

torch.int64

In [57]:
b=torch.FloatTensor([0,1,2,3,4,5])

In [59]:
b.type()

'torch.FloatTensor'

In [61]:
b.dtype

torch.float32

In [67]:
a.type(torch.FloatTensor)

tensor([7., 3., 4., 4., 5., 7.])

In [69]:
a.size()

torch.Size([6])

In [71]:
a.ndimension()

1

In [85]:
#convert 1D to 2D tensor using view method


a_col=a.view(6,1)
a
a.ndimension()

1

In [91]:
# -1 can be used if we don't know no of elements in tensor
a_col=a.view(-1,1)

a
a.ndimension()

1

In [95]:
#  pytorch  tensor to  numpy and numbers

numpy1=a.numpy()
numpy1

array([7, 3, 4, 4, 5, 7], dtype=int64)

In [105]:
np1=np.array([1,2,3,4])
np1

array([1, 2, 3, 4])

In [107]:
tor=torch.from_numpy(np1)
tor

tensor([1, 2, 3, 4], dtype=torch.int32)

In [ ]:
pds=pd.series([0.1,2,3,10.1])